################################
## Airflow Cleanup Pods CronJob
#################################
{{- if .Values.cleanup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleanup
  labels:
    tier: airflow-cleanup-pods
    component: airflow-cleanup-pods
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.cleanup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          nodeSelector:
{{ toYaml .Values.nodeSelector | indent 12 }}
          affinity:
{{ toYaml .Values.affinity | indent 12 }}
          tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
          serviceAccountName: {{ .Release.Name }}-cleanup-serviceaccount
          containers:
            - name: airflow-cleanup-pods
              image: {{ template "airflow_image" . }}
              imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
              args: ["airflow-cleanup-pods", "--namespace={{ .Release.Namespace }}"]
              env:
              {{- include "custom_airflow_environment" . | indent 12 }}
              {{- include "standard_airflow_environment" . | indent 12 }}
{{- end }}
