{
 "title": "Istio Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Istio Proxy CPU Use by Pod",
   "type": "graph",
   "description": "The percent of the limit of CPU each proxy can use. more than 50% may be indicate performance degradation.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(  sum(rate(container_cpu_usage_seconds_total{namespace!~\".*-.*\", container_name=\"istio-proxy\"}[3m])) by (pod_name, container_name, component_name, namespace, short_name)/  sum(container_spec_cpu_quota{namespace!~\".*-.*\", container_name=\"istio-proxy\"}/container_spec_cpu_period{namespace!~\".*-.*\", container_name=\"istio-proxy\"}) by (pod_name, container_name, component_name, namespace, short_name)*100,  \"short_name\",  \"$1\",  \"pod_name\",  \"^[[deployment]]-(.*)$\")",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Istio Proxy CPU Throttling",
   "type": "graph",
   "description": "The percent of period intervals that were throttled by any amount. A period interval is a chunk of CPU time allocated to a container. 100% does not mean that no CPU is available to the container, it just means that the container is being throttled by any amount 100% of the time.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (increase(container_cpu_cfs_throttled_periods_total{namespace!~\".*-.*\", container_name=\"istio-proxy\"}[1m]) / increase(container_cpu_cfs_periods_total{namespace!~\".*-.*\", container_name=\"istio-proxy\"}[1m]))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Istio Proxy Memory Use by Pod",
   "type": "graph",
   "description": "The percent of the limit of memory each proxy can use",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace!~\".*-.*\", container_name=\"istio-proxy\"} / container_spec_memory_limit_bytes{namespace!~\".*-.*\", container_name=\"istio-proxy\"} * 100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Istio Proxy CPU Use by Pod",
     "type": "graph",
     "description": "The percent of the limit of CPU each proxy can use. more than 50% may be indicate performance degradation.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(  sum(rate(container_cpu_usage_seconds_total{namespace=~\".*-.*\", container_name=\"istio-proxy\"}[3m])) by (pod_name, container_name, component_name, namespace, short_name)/  sum(container_spec_cpu_quota{namespace=~\".*-.*\", container_name=\"istio-proxy\"}/container_spec_cpu_period{namespace=~\".*-.*\", container_name=\"istio-proxy\"}) by (pod_name, container_name, component_name, namespace, short_name)*100,  \"short_name\",  \"$1\",  \"pod_name\",  \"^[[deployment]]-(.*)$\")",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Deployment Istio Proxy CPU Throttling",
     "type": "graph",
     "description": "The percent of period intervals that were throttled by any amount. A period interval is a chunk of CPU time allocated to a container. 100% does not mean that no CPU is available to the container, it just means that the container is being throttled by any amount 100% of the time.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (increase(container_cpu_cfs_throttled_periods_total{namespace=~\".*-.*\", container_name=\"istio-proxy\"}[1m]) / increase(container_cpu_cfs_periods_total{namespace=~\".*-.*\", container_name=\"istio-proxy\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Istio Proxy Memory Use by Pod",
     "type": "graph",
     "description": "The percent of the limit of memory each proxy can use",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=~\".*-.*\", container_name=\"istio-proxy\"} / container_spec_memory_limit_bytes{namespace=~\".*-.*\", container_name=\"istio-proxy\"} * 100",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}