################################
## Astronomer Norbit NetworkPolicy
#################################
{{- if .Values.norbit.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-norbit-policy
  labels:
    tier: astronomer
    component: norbit-policy
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: astronomer
      component: norbit
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: nginx
          component: ingress-controller
    ports:
    - protocol: TCP
      port: {{ .Values.ports.norbitHTTP }}
{{- end }}
