################################
## Astronomer Norbit Deployment
#################################
{{- if .Values.norbit.enabled }}
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-norbit
  labels:
    component: norbit
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: norbit
      tier: astronomer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: norbit
        tier: astronomer
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 8 }}
      affinity:
{{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 8 }}
      restartPolicy: Always
      containers:
        - name: norbit
          image: {{- include "norbit.image" . | indent 1 }}
          imagePullPolicy: {{ .Values.images.norbit.pullPolicy }}
          resources:
{{ toYaml .Values.norbit.resources | indent 12 }}
          ports:
            - name: norbit-http
              containerPort: {{ .Values.ports.norbitHTTP }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.norbitHTTP }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.norbitHTTP }}
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            {{- range $i, $config := .Values.norbit.env }}
            - name: {{ $config.name }}
              value: {{ $config.value | quote }}
            {{- end }}
            {{- if .Values.global.baseDomain }}
            - name: APP_API_LOC_HTTPS
              value: "https://houston.{{ .Values.global.baseDomain }}/v1"
            - name: APP_API_LOC_WSS
              value: "wss://houston.{{ .Values.global.baseDomain }}/ws"
            {{- end }}
{{- end }}
